package xyz.iamray.weibomanger.api;


import xyz.iamray.weibomanger.api.impl.CrawlWeiBoByUrlAPI;

/**
 * @author winray
 * @since v1.0.1
 */
public enum APINumber {

    ADDFOLLOWINGTOGROUPAPI,
    CRAWLWEIBOAPI,
    CREATENEWFOLLOWINGGROUPAPI,
    DELIVERBLOGAPI,
    FOLLOWWEIBOERAPI,
    FORWARDBLOGAPI,
    GETHOTCOMMENTAPI,
    GETWEIBOERSFROMGROUPCHATAPI,
    LOGINAPI,
    SENDGROUPMESSAGEAPI,
    SENDPRIVATELETTERAPI,
    UPLOADIMAGEAPI,
    GETMOBALHOTCOMMENTAPI,
    CRAWLWEIBOBYURLAPI,
    CRAWLMOBALHOTLISTAPI,
    GETMOBALWEIBOBYURLAPI;
}
